### ISSUE TITLE
Add doctests

### ISSUE THREAD

**Issue by Firionus** [deltaeight/LibArtNet#2]
**Is your feature request related to a problem? Please describe.**
#1 fixed an example in README that didn't compile due to a recent commit. 

**Describe the solution you'd like**
All examples should be doctests.

**Describe alternatives you've considered**
None. 

**Additional context**
I'm totally new to Java and have no idea yet how to do doctests.

**Comment by schw4rzlicht** [comment]
Hey @Firionus, good idea. I pushed some tests to verify doc code, my only concern is that when there is a breaking change introduced, IDE refactoring also keeps the tests alive, so that won't help so much with keeping the docs healthy, but it doesn't hurt either :)
